# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3069ebeff02afac15a02a1ed01e51849ce8d929eb2a8783bab0fe7ceaedebe90147c22b06718268f792209642986e44ee0ae07bff243b95e081b74079f15da7

test:
  secret_key_base: d325abd263531de80af28754c2c792c740be007c320f6dd5f5fa5e1a6519114e3de86b7f6c7c5a5adb14a9b872984a962e74ba1ce0655d39530e6b8c281ab45b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
